version: '3.5'
services:
  mockserver:
    build: mockserver
    ports: ['8001:8000']
    volumes:
      - './mockserver/public:/home/public'
      - './mockserver/server.py:/home/server.py'
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
        - eu.gcr.io/tmrow-152415/electricitymap_web:staging
        - eu.gcr.io/tmrow-152415/electricitymap_web:latest
    image: eu.gcr.io/tmrow-152415/electricitymap_web:latest
    command: npm run server-dev
    depends_on: ['mockserver']
    environment:
      - NODE_ENV=development
    ports: ['8000:8000']
    volumes:
      - './config:/home/config'
      - './web/.eslintrc:/home/src/electricitymap/contrib/web/.eslintrc'
      - './web/geo:/home/src/electricitymap/contrib/web/geo'
      - './web/locales:/home/src/electricitymap/contrib/web/locales'
      - './web/locales-config.json:/home/src/electricitymap/contrib/web/locales-config.json'
      - './web/package.json:/home/src/electricitymap/contrib/web/package.json'
      - './web/public:/home/src/electricitymap/contrib/web/public'
      - './web/server.js:/home/src/electricitymap/contrib/web/server.js'
      - './web/src:/home/src/electricitymap/contrib/web/src'
      - './web/views:/home/src/electricitymap/contrib/web/views'
      - './web/webpack.config.js:/home/src/electricitymap/contrib/web/webpack.config.js'
  web-watch:
    build:
      context: .
      dockerfile: web/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
        - eu.gcr.io/tmrow-152415/electricitymap_web:staging
        - eu.gcr.io/tmrow-152415/electricitymap_web:latest
    image: eu.gcr.io/tmrow-152415/electricitymap_web:latest
    command: npm run watch
    environment:
      - NODE_ENV=development
    volumes:
      - './config:/home/config'
      - './web/.eslintrc:/home/src/electricitymap/contrib/web/.eslintrc'
      - './web/geo:/home/src/electricitymap/contrib/web/geo'
      - './web/locales:/home/src/electricitymap/contrib/web/locales'
      - './web/locales-config.json:/home/src/electricitymap/contrib/web/locales-config.json'
      - './web/package.json:/home/src/electricitymap/contrib/web/package.json'
      - './web/public:/home/src/electricitymap/contrib/web/public'
      - './web/server.js:/home/src/electricitymap/contrib/web/server.js'
      - './web/src:/home/src/electricitymap/contrib/web/src'
      - './web/views:/home/src/electricitymap/contrib/web/views'
      - './web/webpack.config.js:/home/src/electricitymap/contrib/web/webpack.config.js'
