[tool.poetry]
name = "electricitymap-contrib"
version = "0.1.0"
description = ""
authors = ["electricityMap team <hello@electricityMap.org>"]
packages = [
    { include = "electricitymap" }
]
include = ["config/*.json"]

[tool.poetry.dependencies]
python = '>= 3.7.1, < 4.0'
pydantic = "^1.8.2"

arrow = {version="0.16.0", optional=true}
beautifulsoup4 = {version="4.6.0", optional=true}
demjson3 = {version="3.0.5", optional=true}
eiapy = {version = "0.1.6", optional=true}
freezegun = {version="0.3.15", optional=true}
html5lib = {version="0.999999999", optional=true}
imageio = {version="2.8.0", optional=true}
lxml = {version="4.6.5", optional=true}
mock = {version="2.0.0", optional=true}
opencv-python = {version="4.4.0.46", optional=true}
pandas = {version="1.3.5", optional=true}
Pillow = {version="9.0.0", optional=true}
pytesseract = {version="0.2.0", optional=true}
ree = {version="2.2.1", optional=true}
requests = {version="2.25.1", optional=true}
signalr-client-threads = {version="0.0.12", optional=true}
tablib = {version="0.12.1", optional=true}
tqdm = {version="^4.60.0", optional=true}
xlrd = {version="1.2.0", optional=true}

[tool.poetry.dev-dependencies]
click = "8.0.1"
flake8 = "^3.8.4"
mock = "2.0.0"
pylint = "^2.6.0"
requests-mock = "1.3.0"
testfixtures = "6.0.0"

[tool.poetry.scripts]
lint = 'scripts:lint'
test = 'scripts:test'
test-parser = 'test_parser:test_parser'
test_parser = 'test_parser:test_parser'

[tool.poetry.extras]
parsers = [
    "arrow",
    "beautifulsoup4",
    "demjson3",
    "eiapy",
    "html5lib",
    "imageio",
    "lxml",
    "mock",
    "pandas",
    "Pillow",
    "pytesseract",
    "ree",
    "requests",
    "tablib",
    "opencv-python",
    "xlrd",
    "freezegun",
    "signalr-client-threads",
    "tqdm"
]

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
